enabled: false

samples:
  - id: ttbar_faketau
    label: "fake taus"
  - id: wtaunu_faketau
    label: "fake taus"
  - id: wmunu_faketau
    label: "fake taus"
  - id: wenu_faketau
    label: "fake taus"
  - id: ztautau_faketau
    label: "fake taus"
  - id: zmumu_faketau
    label: "fake taus"
  - id: zee_faketau
    label: "fake taus"
  - id: znunu_faketau
    label: "fake taus"
  - id: diboson_faketau
    label: "fake taus"
  - id: higgs_faketau
    label: "fake taus"
  - id: singletop_faketau
    label: "fake taus"
  - id: ttX_faketau
    label: "fake taus"

exclude:
  - higgs_faketau
  - ttX_faketau
