background_strategy: "as_primary"
signal_strategy: "as_one"

primary_groups:
  topquarks:
    - ttbar
    - singletop
  wtaunu:
    - wtaunu
  ztautau:
    - ztautau
  diboson:
    - diboson

signal_type_names:
  GG: gluinos
  SS: squarks

mass_thresholds:
  gluinos: [1000, 1700]
  squarks: [800, 1400]
